version: '3'
services:
  nginx:
    build: ./docker/nginx
    container_name: nginx
    extra_hosts:
      - board:127.0.0.1
    networks:
      - mynet
    ports:
      - 8080:80

  mysql8:
    build: ./docker/mysql
    container_name: mysql8
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - mynet
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer
    container_name: adminer
    networks:
      - mynet
    ports:
      - 3304:8080

  app:
    build: .
    container_name: board
    depends_on:
      - mysql8
    links:
      - mysql8
    networks:
      - mynet
    extra_hosts:
      - board:127.0.0.1
    ports:
      - 80:7001
    command: ["sh", "-c", "npx sequelize db:migrate | npm run dev"]

networks:
  mynet:
    driver: bridge
